# Generated by Django 3.2.22 on 2023-11-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20231110_0307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
